### ISSUE TITLE
redirect remaining funds back to original sending address

### ISSUE THREAD

**Issue by kendricktan** [ZencashOfficial/zenchat#1]
as per title

**Comment by blockops1** [comment]
you can do this if you make the sending address a shielded address. But then you need to come up with a different way to track identity of chat participant, I think.

**Comment by kendricktan** [comment]
fixed in https://github.com/ZencashOfficial/zenchat/commit/a8534d748b2e5f4f7380d2660d2a69de1dda3d7b
