### ISSUE TITLE
FR: self destructing messages

### ISSUE THREAD

**Issue by ITwrx** [ZencashOfficial/zenchat#3]
is there any way to allow for self destructing messages after a set time, at the sender's discretion? This would solve the problem of messages being decrypted later due to advances in technology or vulnerabilites found in zenchat or underlying software. Maybe initial messages could be sent without writing to the blockchain (using omemo maybe) and only permanent (or public) messages end up getting written to the blockchain? Interception of the temporary messages would at least require a specific real-time decryption capability from an adversary. 

Messaging could potentially provide much more useful info to adversaries when compared to addresses and amounts alone, and users will not necessarily understand the long term risks they are taking when sending messages they believe to be "secure" (whatever that means at any given time to any given person). 

thanks

**Comment by kendricktan** [comment]
Unfortunately no, the whole point of a blockchain is that it is immutable, the only other way I can think of is if you send a message containing a temporary link and disable it when you would like to 'destroy' the message.

**Comment by leto** [comment]
Any "self destructing" message can be defeated by taking a photo of a screen with another device, and things will be recorded on the blockchain for all of time. It's a hard problem that even Signal cannot get correct, their "disappearing messages" do not work reliably at all

**Comment by ITwrx** [comment]
maybe i wasn't clear, but that's why i was saying that the self destructing messages could happen independently of any blockchain transaction. A p2p xmpp+omemo server and client that shreds the messages after being read or after a time period. This feature may be too much work and/or out of scope for zencash/zenchat and that's fine, if so. I guess it just depends how zenchat's features/use case are presented to users.
